import type { DesignTokenSet } from '@fetchtype/types';

type TailwindOptions = {
  prefix?: string;
};

function formatFontFamily(fontFamily: string | string[]): string[] {
  return Array.isArray(fontFamily) ? fontFamily : [fontFamily];
}

function indent(level: number): string {
  return '  '.repeat(level);
}

function quote(value: string): string {
  return `'${value}'`;
}

export function generateTailwindConfig(
  tokenSet: DesignTokenSet,
  _options?: TailwindOptions,
): string {
  const lines: string[] = ['// Generated by fetchtype', 'export default {'];
  const i1 = indent(1);
  const i2 = indent(2);
  const i3 = indent(3);

  // -- theme --
  lines.push(`${i1}theme: {`);

  // -- fontSize --
  lines.push(`${i2}fontSize: {`);
  for (const [context, token] of Object.entries(tokenSet.typography)) {
    const meta: string[] = [];
    meta.push(`lineHeight: ${quote(String(token.lineHeight))}`);
    meta.push(`fontWeight: ${quote(String(token.fontWeight))}`);
    if (token.letterSpacing) {
      meta.push(`letterSpacing: ${quote(token.letterSpacing)}`);
    }
    lines.push(
      `${i3}${quote(context)}: [${quote(String(token.fontSize))}, { ${meta.join(', ')} }],`,
    );
  }
  lines.push(`${i2}},`);

  // -- fontFamily --
  lines.push(`${i2}fontFamily: {`);
  const emittedFamilyContexts = new Set<string>();
  for (const [context, token] of Object.entries(tokenSet.typography)) {
    const familyKey = JSON.stringify(token.fontFamily);
    if (emittedFamilyContexts.has(familyKey)) {
      continue;
    }
    emittedFamilyContexts.add(familyKey);
    const families = formatFontFamily(token.fontFamily).map(quote).join(', ');
    lines.push(`${i3}${quote(context)}: [${families}],`);
  }
  lines.push(`${i2}},`);

  // -- colors --
  lines.push(`${i2}colors: {`);
  for (const [groupName, group] of Object.entries(tokenSet.color.light)) {
    for (const [tokenName, tokenValue] of Object.entries(group)) {
      lines.push(`${i3}${quote(`${groupName}-${tokenName}`)}: ${quote(tokenValue.value)},`);
    }
  }
  lines.push(`${i2}},`);

  // -- spacing --
  lines.push(`${i2}spacing: {`);
  for (const [name, value] of Object.entries(tokenSet.spacing.scale)) {
    lines.push(`${i3}${quote(name)}: ${quote(value)},`);
  }
  lines.push(`${i2}},`);

  // -- maxWidth --
  lines.push(`${i2}maxWidth: {`);
  for (const [name, value] of Object.entries(tokenSet.layout.maxWidth)) {
    lines.push(`${i3}${quote(name)}: ${quote(value)},`);
  }
  lines.push(`${i2}},`);

  // close theme and default export
  lines.push(`${i1}},`);
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
