import { describe, expect, it } from 'vitest';

import { DEFAULT_TOKEN_SET, resolveDesignTokenSet } from '../index.js';
import { generateTailwindConfig } from './tailwind.js';

describe('generateTailwindConfig', () => {
  const resolved = resolveDesignTokenSet(DEFAULT_TOKEN_SET);

  it('contains fontSize entries for each typography context', () => {
    const config = generateTailwindConfig(resolved);

    for (const context of Object.keys(resolved.typography)) {
      expect(config).toContain(`'${context}':`);
    }

    expect(config).toContain('fontSize');
  });

  it('includes line-height and font-weight metadata in fontSize entries', () => {
    const config = generateTailwindConfig(resolved);

    expect(config).toContain('lineHeight');
    expect(config).toContain('fontWeight');
  });

  it('maps colors from light mode with group-token naming', () => {
    const config = generateTailwindConfig(resolved);

    expect(config).toContain("'text-primary':");
    expect(config).toContain("'background-primary':");
    expect(config).toContain("'border-default':");
    expect(config).toContain("'interactive-default':");
  });

  it('includes spacing scale values', () => {
    const config = generateTailwindConfig(resolved);

    for (const name of Object.keys(resolved.spacing.scale)) {
      expect(config).toContain(`'${name}':`);
    }
  });

  it('includes layout maxWidth values', () => {
    const config = generateTailwindConfig(resolved);

    expect(config).toContain("'prose':");
    expect(config).toContain("'content':");
    expect(config).toContain('maxWidth');
  });

  it('starts with the generated-by comment', () => {
    const config = generateTailwindConfig(resolved);

    expect(config.startsWith('// Generated by fetchtype')).toBe(true);
  });

  it('deduplicates fontFamily entries with the same stack', () => {
    const config = generateTailwindConfig(resolved);
    const fontFamilySection = config.slice(
      config.indexOf('fontFamily'),
      config.indexOf('},', config.indexOf('fontFamily')) + 2,
    );

    // Count entries — should be fewer than total typography contexts if families overlap
    const entryCount = (fontFamilySection.match(/^\s+'[^']+': \[/gm) || []).length;
    const contextCount = Object.keys(resolved.typography).length;

    expect(entryCount).toBeLessThanOrEqual(contextCount);
  });
});
